stages:
  train:
    cmd: python pipeline/training_pipeline.py
    deps:
      # Raw data – main trigger for re-running
      - artifacts/raw

      # Pipeline script
      - pipeline/training_pipeline.py

    outs:
      # All artifacts produced by training
      - artifacts/processed
      - artifacts/model
      - artifacts/model_checkpoints
      - artifacts/weights
